[package]
name = "character_sheet"
version = "0.1.0"
edition = "2024"

[dependencies]
iced = {version = "0.14.0",features = ["advanced"]}
iced_aw = { version = "0.13.0", features = ["full"] }
rfd = "0.16.0"
serde = {version = "1.0.228", features = ["derive"]}
serde_json = "1.0.146"
